services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"     #changed
    volumes:
      - ./heatmap-api:/usr/src/app
    environment:
      - NODE_ENV=development
